ALTER TABLE _sqlx_migrations 
ENABLE ROW LEVEL SECURITY;

ALTER TABLE profiles 
ENABLE ROW LEVEL SECURITY;

ALTER TABLE test_users 
ENABLE ROW LEVEL SECURITY;

ALTER TABLE users 
ENABLE ROW LEVEL SECURITY;
